name: Mynode
on: 
  workflow_dispatch:
 
jobs:
 node-1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         go: [1]
         flag: [A, B, C, D, E]
    timeout-minutes: 360
 
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: mkdir runner
      - name: Setup App
        working-directory: ./runner
        run: |
            echo 'OK'
            sleep 50
